apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app-nhfb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app-nhfb
    app.kubernetes.io/part-of: nodejs-users
  name: simple-nodejs-app-nhfb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: simple-nodejs-app-nhfb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: simple-nodejs-app-nhfb
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-ihxd-tenant/nodejs-users/simple-nodejs-app-nhfb@sha256:ce0cc688da68b4cc5de033e343be34a0667ab1a39ac62ecff902b392bfdea7ab
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
